### ISSUE TITLE
Cannot import psycopg2

### ISSUE THREAD

**Issue by ysimonson** [stevepeak/tornpsql#2]
So this is strange, when I try to run the tests I get an import error for psycopg2.

When I run `make venv test`, the psycopg2 dependency seems to install fine:

    Installed /Users/ysimonson/Desktop/nutrino/tornpsql/venv/lib/python2.7/site-packages/psycopg2-2.5.2-py2.7-macosx-10.9-x86_64.egg
    Finished processing dependencies for tornpsql==1.0.2

But once it gets to the tests, a wall of failures:

    ======================================================================
    ERROR: Failure: ImportError (No module named psycopg2)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
        addr.filename, addr.module)
      File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/Users/ysimonson/Desktop/nutrino/tornpsql/tests/tests.py", line 3, in <module>
        import tornpsql
      File "/Users/ysimonson/Desktop/nutrino/tornpsql/tornpsql/__init__.py", line 5, in <module>
        import psycopg2
    ImportError: No module named psycopg2

    ----------------------------------------------------------------------

Any idea what's going on? 

I'm able to use psycopg2 with virtualenv fine in other projects. And psycopg2 imports fine via the repl with virtualenv activated.

**Comment by ysimonson** [comment]
Closing since this change is in develop
